# Generated by Django 4.1.2 on 2022-10-31 04:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_appe', '0006_alter_productreview_options_wishlist'),
    ]

    operations = [
        migrations.AddField(
            model_name='cartorder',
            name='order_status',
            field=models.CharField(choices=[('process', 'In Process'), ('Shipped', 'Shipped'), ('Delivered', 'Delivered')], default='process', max_length=150),
        ),
    ]
